//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoFlagship.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoFlagship.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 装甲空母 的本地化字符串。
        /// </summary>
        internal static string acv {
            get {
                return ResourceManager.GetString("acv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Arsenal {
            get {
                object obj = ResourceManager.GetObject("Arsenal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 水上机母舰 的本地化字符串。
        /// </summary>
        internal static string av {
            get {
                return ResourceManager.GetString("av", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水上机母舰(敌) 的本地化字符串。
        /// </summary>
        internal static string av_e {
            get {
                return ResourceManager.GetString("av_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Battle_Back {
            get {
                object obj = ResourceManager.GetObject("Battle_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Battle_Compass {
            get {
                object obj = ResourceManager.GetObject("Battle_Compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Battle_Formation {
            get {
                object obj = ResourceManager.GetObject("Battle_Formation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Battle_Next {
            get {
                object obj = ResourceManager.GetObject("Battle_Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Battle_Night {
            get {
                object obj = ResourceManager.GetObject("Battle_Night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Battle_Return {
            get {
                object obj = ResourceManager.GetObject("Battle_Return", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 战舰 的本地化字符串。
        /// </summary>
        internal static string bb {
            get {
                return ResourceManager.GetString("bb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空战舰 的本地化字符串。
        /// </summary>
        internal static string bbv {
            get {
                return ResourceManager.GetString("bbv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重巡洋舰 的本地化字符串。
        /// </summary>
        internal static string ca {
            get {
                return ResourceManager.GetString("ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空巡洋舰 的本地化字符串。
        /// </summary>
        internal static string cav {
            get {
                return ResourceManager.GetString("cav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轻巡洋舰 的本地化字符串。
        /// </summary>
        internal static string cl {
            get {
                return ResourceManager.GetString("cl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重雷装巡洋舰 的本地化字符串。
        /// </summary>
        internal static string clt {
            get {
                return ResourceManager.GetString("clt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空母舰 的本地化字符串。
        /// </summary>
        internal static string cv {
            get {
                return ResourceManager.GetString("cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轻空母 的本地化字符串。
        /// </summary>
        internal static string cvl {
            get {
                return ResourceManager.GetString("cvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱逐舰 的本地化字符串。
        /// </summary>
        internal static string dd {
            get {
                return ResourceManager.GetString("dd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高速战舰 的本地化字符串。
        /// </summary>
        internal static string fbb {
            get {
                return ResourceManager.GetString("fbb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扬陆舰 的本地化字符串。
        /// </summary>
        internal static string ls {
            get {
                return ResourceManager.GetString("ls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MainPort {
            get {
                object obj = ResourceManager.GetObject("MainPort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MainPort_Left {
            get {
                object obj = ResourceManager.GetObject("MainPort_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MainPort_title {
            get {
                object obj = ResourceManager.GetObject("MainPort_title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MainPort_title1 {
            get {
                object obj = ResourceManager.GetObject("MainPort_title1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Map {
            get {
                object obj = ResourceManager.GetObject("Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Map_Decide {
            get {
                object obj = ResourceManager.GetObject("Map_Decide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Map_Start_False {
            get {
                object obj = ResourceManager.GetObject("Map_Start_False", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Map_Start_False2 {
            get {
                object obj = ResourceManager.GetObject("Map_Start_False2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Map_Start_True {
            get {
                object obj = ResourceManager.GetObject("Map_Start_True", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Mission {
            get {
                object obj = ResourceManager.GetObject("Mission", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Mission_Decide {
            get {
                object obj = ResourceManager.GetObject("Mission_Decide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Mission_Start_False {
            get {
                object obj = ResourceManager.GetObject("Mission_Start_False", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Mission_Start_True {
            get {
                object obj = ResourceManager.GetObject("Mission_Start_True", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Organize {
            get {
                object obj = ResourceManager.GetObject("Organize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Organize_Change_Decide_False {
            get {
                object obj = ResourceManager.GetObject("Organize_Change_Decide_False", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Organize_Change_Decide_True {
            get {
                object obj = ResourceManager.GetObject("Organize_Change_Decide_True", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Organize_ShipSelect {
            get {
                object obj = ResourceManager.GetObject("Organize_ShipSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Organize_SortByNew {
            get {
                object obj = ResourceManager.GetObject("Organize_SortByNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 练习巡洋舰 的本地化字符串。
        /// </summary>
        internal static string pcl {
            get {
                return ResourceManager.GetString("pcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Practice {
            get {
                object obj = ResourceManager.GetObject("Practice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Quest {
            get {
                object obj = ResourceManager.GetObject("Quest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Remodel {
            get {
                object obj = ResourceManager.GetObject("Remodel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Remodel_ItemList {
            get {
                object obj = ResourceManager.GetObject("Remodel_ItemList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Remodel_ItemList_Decide_True {
            get {
                object obj = ResourceManager.GetObject("Remodel_ItemList_Decide_True", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Remodel_ItemList_Normal {
            get {
                object obj = ResourceManager.GetObject("Remodel_ItemList_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Remodel_ItemList_Other_Decide {
            get {
                object obj = ResourceManager.GetObject("Remodel_ItemList_Other_Decide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Remodel_Remodel_False {
            get {
                object obj = ResourceManager.GetObject("Remodel_Remodel_False", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Remodel_Remodel_True {
            get {
                object obj = ResourceManager.GetObject("Remodel_Remodel_True", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Repair {
            get {
                object obj = ResourceManager.GetObject("Repair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Repair_ShipSelect {
            get {
                object obj = ResourceManager.GetObject("Repair_ShipSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Repair_SortByNew {
            get {
                object obj = ResourceManager.GetObject("Repair_SortByNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Repair_Start_False {
            get {
                object obj = ResourceManager.GetObject("Repair_Start_False", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Repair_Start_True {
            get {
                object obj = ResourceManager.GetObject("Repair_Start_True", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Sally {
            get {
                object obj = ResourceManager.GetObject("Sally", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 补给舰 的本地化字符串。
        /// </summary>
        internal static string sp {
            get {
                return ResourceManager.GetString("sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 潜水艇 的本地化字符串。
        /// </summary>
        internal static string ss {
            get {
                return ResourceManager.GetString("ss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 潜水母舰 的本地化字符串。
        /// </summary>
        internal static string ssm {
            get {
                return ResourceManager.GetString("ssm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 潜水空母 的本地化字符串。
        /// </summary>
        internal static string ssv {
            get {
                return ResourceManager.GetString("ssv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海防艦 的本地化字符串。
        /// </summary>
        internal static string stype1 {
            get {
                return ResourceManager.GetString("stype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空戦艦 的本地化字符串。
        /// </summary>
        internal static string stype10 {
            get {
                return ResourceManager.GetString("stype10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正規空母 的本地化字符串。
        /// </summary>
        internal static string stype11 {
            get {
                return ResourceManager.GetString("stype11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超弩級戦艦 的本地化字符串。
        /// </summary>
        internal static string stype12 {
            get {
                return ResourceManager.GetString("stype12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 潜水艦 的本地化字符串。
        /// </summary>
        internal static string stype13 {
            get {
                return ResourceManager.GetString("stype13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 潜水空母 的本地化字符串。
        /// </summary>
        internal static string stype14 {
            get {
                return ResourceManager.GetString("stype14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 補給艦 的本地化字符串。
        /// </summary>
        internal static string stype15 {
            get {
                return ResourceManager.GetString("stype15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水上機母艦 的本地化字符串。
        /// </summary>
        internal static string stype16 {
            get {
                return ResourceManager.GetString("stype16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 揚陸艦 的本地化字符串。
        /// </summary>
        internal static string stype17 {
            get {
                return ResourceManager.GetString("stype17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装甲空母 的本地化字符串。
        /// </summary>
        internal static string stype18 {
            get {
                return ResourceManager.GetString("stype18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作艦 的本地化字符串。
        /// </summary>
        internal static string stype19 {
            get {
                return ResourceManager.GetString("stype19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 駆逐艦 的本地化字符串。
        /// </summary>
        internal static string stype2 {
            get {
                return ResourceManager.GetString("stype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 潜水母艦 的本地化字符串。
        /// </summary>
        internal static string stype20 {
            get {
                return ResourceManager.GetString("stype20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 練習巡洋艦 的本地化字符串。
        /// </summary>
        internal static string stype21 {
            get {
                return ResourceManager.GetString("stype21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 補給艦 的本地化字符串。
        /// </summary>
        internal static string stype22 {
            get {
                return ResourceManager.GetString("stype22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 軽巡洋艦 的本地化字符串。
        /// </summary>
        internal static string stype3 {
            get {
                return ResourceManager.GetString("stype3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重雷装巡洋艦 的本地化字符串。
        /// </summary>
        internal static string stype4 {
            get {
                return ResourceManager.GetString("stype4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重巡洋艦 的本地化字符串。
        /// </summary>
        internal static string stype5 {
            get {
                return ResourceManager.GetString("stype5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空巡洋艦 的本地化字符串。
        /// </summary>
        internal static string stype6 {
            get {
                return ResourceManager.GetString("stype6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 軽空母 的本地化字符串。
        /// </summary>
        internal static string stype7 {
            get {
                return ResourceManager.GetString("stype7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦艦 的本地化字符串。
        /// </summary>
        internal static string stype8 {
            get {
                return ResourceManager.GetString("stype8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦艦 的本地化字符串。
        /// </summary>
        internal static string stype9 {
            get {
                return ResourceManager.GetString("stype9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Supply {
            get {
                object obj = ResourceManager.GetObject("Supply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Wo改 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string unkown {
            get {
                return ResourceManager.GetString("unkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作舰 的本地化字符串。
        /// </summary>
        internal static string ws {
            get {
                return ResourceManager.GetString("ws", resourceCulture);
            }
        }
    }
}
